SCREEN_WIDTH = 1920
SCREEN_HEIGHT = 1080
WRAP_AROUND = True

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 4
ASTEROID_SPAWN_RATE = 1.0  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 250
PLAYER_MAX_SPEED = 800
PLAYER_ACCELERATION = 500
PLAYER_FRICTION = 0.995

SHOT_RADIUS = 5
SHOT_LIFETIME = 4.0
PLAYER_SHOT_SPEED = 500
PLAYER_SHOT_COOLDOWN = 0.3

POWERUP_SPAWN_RATE = 20.0
POWERUP_LIFETIME = 10.0
POWERUP_DURATION = 10.0